# Digital Payments Analytics (UPI - 2024)

## Project Overview

This project analyzes over 250,000 UPI transactions to understand transaction trends, bank performance, fraud patterns, merchant performance, customer behavior, and digital payment usage.

### Tools Used
- Python
- Pandas
- NumPy
- Power BI

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("C:/Users/pooja/OneDrive/Documents/Digital Payments Analytics/Dataset/upi_transactions_2024.csv")

# Dataset Overview

In [5]:
df.head()

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction id      250000 non-null  object
 1   timestamp           250000 non-null  object
 2   transaction type    250000 non-null  object
 3   merchant_category   250000 non-null  object
 4   amount (INR)        250000 non-null  int64
 5   transaction_status  250000 non-null  object
 6   sender_age_group    250000 non-null  object
 7   receiver_age_group  250000 non-null  object
 8   sender_state        250000 non-null  object
 9   sender_bank         250000 non-null  object
 10  receiver_bank       250000 non-null  object
 11  device_type         250000 non-null  object
 12  network_type        250000 non-null  object
 13  fraud_flag          250000 non-null  int64
 14  hour_of_day         250000 non-null  int64
 15  day_of_week         250000 non-null  object
 16  is_weekend          250000 non-null  int64
dtypes: int64(4), object(13)
memory usage: 32.4+ MB

In [7]:
df.describe()

        amount (INR)     fraud_flag    hour_of_day     is_weekend
count  250000.000000  250000.000000  250000.000000  250000.000000
mean     1311.756036       0.001920      14.681032       0.285348
std      1848.059224       0.043776       5.188304       0.451581
min        10.000000       0.000000       0.000000       0.000000
25%       288.000000       0.000000      11.000000       0.000000
50%       629.000000       0.000000      15.000000       0.000000
75%      1596.000000       0.000000      19.000000       1.000000
max     42099.000000       1.000000      23.000000       1.000000

In [8]:
df.shape

(250000, 17)

In [10]:
df.columns

Index(['transaction id', 'timestamp', 'transaction type', 'merchant_category',
       'amount (INR)', 'transaction_status', 'sender_age_group',
       'receiver_age_group', 'sender_state', 'sender_bank', 'receiver_bank',
       'device_type', 'network_type', 'fraud_flag', 'hour_of_day',
       'day_of_week', 'is_weekend'],
      dtype='object')

# Data Cleaning

In [11]:
df.isnull().sum()

transaction id        0
timestamp             0
transaction type      0
merchant_category     0
amount (INR)          0
transaction_status    0
sender_age_group      0
receiver_age_group    0
sender_state          0
sender_bank           0
receiver_bank         0
device_type           0
network_type          0
fraud_flag            0
hour_of_day           0
day_of_week           0
is_weekend            0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.dtypes

transaction id        object
timestamp             object
transaction type      object
merchant_category     object
amount (INR)           int64
transaction_status    object
sender_age_group      object
receiver_age_group    object
sender_state          object
sender_bank           object
receiver_bank         object
device_type           object
network_type          object
fraud_flag             int64
hour_of_day            int64
day_of_week           object
is_weekend             int64
dtype: object

# Feature Engineering

In [14]:
def category(amount):
    if amount < 1000:
        return "Small"
    elif amount < 5000:
        return "Medium"
    else:
        return "Large"

df["transaction_size"] = df["amount (INR)"].apply(category)

In [16]:
df["day_type"] = df["is_weekend"].map(
    {
        1: "Weekend",
        0: "Weekday"
    }
)

In [17]:
df["status_code"] = df["transaction_status"].map(
    {
        "SUCCESS": 1,
        "FAILED": 0
    }
)

# Exploratory Data Analysis

## Q1. Top 5 Sender Banks by Revenue

In [18]:
df.groupby("sender_bank")["amount (INR)"]\
.sum()\
.sort_values(ascending=False)\
.head(5)

sender_bank
SBI         82816520
HDFC        49791194
ICICI       38731193
IndusInd    32842711
Yes Bank    32492477
Name: amount (INR), dtype: int64

## Q2. Top 5 Receiver Banks by Revenue

In [19]:
df.groupby("receiver_bank")["amount (INR)"]\
.sum()\
.sort_values(ascending=False)\
.head(5)

receiver_bank
SBI         82565386
HDFC        49157476
ICICI       39029938
Axis        33007678
Yes Bank    32838599
Name: amount (INR), dtype: int64

## Q3. Revenue by Sender State

In [20]:
df.groupby("sender_state")["amount (INR)"]\
.sum()\
.sort_values(ascending=False)

sender_state
Maharashtra       49043948
Uttar Pradesh     40035717
Karnataka         38451158
Tamil Nadu        33343518
Delhi             32689865
Telangana         29750930
Rajasthan         26730470
Gujarat           25988190
Andhra Pradesh    25952619
West Bengal       25952594
Name: amount (INR), dtype: int64

## Q4. Average Transaction Amount by Transaction Type

In [22]:
df.groupby("transaction type")["amount (INR)"]\
.mean()\
.sort_values(ascending=False)

transaction type
P2M             1320.072633
P2P             1308.681115
Bill Payment    1308.492373
Recharge        1290.895745
Name: amount (INR), dtype: float64

# Exploratory Data Analysis (Business Questions)

## Top 5 sender banks by total transaction revenue?

In [23]:
df.groupby("sender_bank")["amount (INR)"] \
.sum() \
.sort_values(ascending=False) \
.head(5)

sender_bank
SBI         82816520
HDFC        49791194
ICICI       38731193
IndusInd    32842711
Yes Bank    32492477
Name: amount (INR), dtype: int64

## Top 5 receiver banks by total transaction revenue?

In [24]:
df.groupby("receiver_bank")["amount (INR)"] \
.sum() \
.sort_values(ascending=False) \
.head(5)

receiver_bank
SBI         82565386
HDFC        49157476
ICICI       39029938
Axis        33007678
Yes Bank    32838599
Name: amount (INR), dtype: int64

## Revenue by Sender State

In [25]:
df.groupby("sender_state")["amount (INR)"] \
.sum() \
.sort_values(ascending=False)

sender_state
Maharashtra       49043948
Uttar Pradesh     40035717
Karnataka         38451158
Tamil Nadu        33343518
Delhi             32689865
Telangana         29750930
Rajasthan         26730470
Gujarat           25988190
Andhra Pradesh    25952619
West Bengal       25952594
Name: amount (INR), dtype: int64

## Revenue by Merchant Category

In [26]:
df.groupby("merchant_category")["amount (INR)"] \
.sum() \
.sort_values(ascending=False)

merchant_category
Shopping         76863207
Grocery          58277893
Utilities        52742482
Fuel             38982575
Education        38704346
Other            21073449
Food             19919402
Entertainment     8309080
Healthcare        6874159
Transport         6192416
Name: amount (INR), dtype: int64

## Average Transaction by Transaction Type

In [28]:
df.groupby("transaction type")["amount (INR)"] \
.mean() \
.sort_values(ascending=False)

transaction type
P2M             1320.072633
P2P             1308.681115
Bill Payment    1308.492373
Recharge        1290.895745
Name: amount (INR), dtype: float64

## Overall Transaction Success Rate

In [30]:
success = df[df["transaction_status"] == "SUCCESS"].shape[0]
total = df.shape[0]

(success / total) * 100

95.0496

## Overall transaction failure rate

In [31]:
failure = df[df["transaction_status"] == "FAILED"].shape[0]
total = df.shape[0]

(failure / total) * 100

4.9504

## Fraud Rate by Sender Bank

In [32]:
fraud = df[df["fraud_flag"] == 1].groupby("sender_bank")["fraud_flag"].count()

total = df.groupby("sender_bank")["fraud_flag"].count()

((fraud / total) * 100).sort_values(ascending=False)

sender_bank
Kotak       0.249601
ICICI       0.221707
PNB         0.208450
IndusInd    0.206571
Axis        0.195671
SBI         0.173863
HDFC        0.165399
Yes Bank    0.160901
Name: fraud_flag, dtype: float64

## Revenue by Sender Age Group

In [34]:
df.groupby("sender_age_group")["amount (INR)"] \
.sum() \
.sort_values(ascending=False)

sender_age_group
26-35    115959771
36-45     89533745
18-25     74473936
46-55     33116261
56+       14855296
Name: amount (INR), dtype: int64

## Transactions by Network Type

In [37]:
df.groupby("network_type")["transaction id"].count()

network_type
3G       12471
4G      149813
5G       62582
WiFi     25134
Name: transaction id, dtype: int64

### Key Insights

- SBI generated the highest transaction revenue.
- Shopping was the top merchant category.
- The overall success rate exceeded 95%.
- Fraud rates remained very low across banks.
- The 26–35 age group contributed the highest revenue.

## Transactions by device type

In [39]:
df.groupby("device_type")["transaction id"].count().sort_values(ascending=False)

device_type
Android    187777
iOS         49613
Web         12610
Name: transaction id, dtype: int64

## Hourly Transactions

In [42]:
df.groupby("hour_of_day")["transaction id"].count()

hour_of_day
0      3388
1      2244
2      1685
3      1314
4      1247
5      1742
6      3501
7      5630
8      8349
9     10450
10    13904
11    16328
12    17516
13    15038
14    11472
15    12624
16    13992
17    18340
18    20064
19    21232
20    18506
21    16253
22     9364
23     5817
Name: transaction id, dtype: int64

## Weekday Vs Weekend Revenue

In [43]:
df.groupby("day_type")["amount (INR)"].sum()

day_type
Weekday    234498529
Weekend     93440480
Name: amount (INR), dtype: int64

## Success Vs Failure transactions

In [45]:
df.groupby("transaction_status")["transaction id"].count()

transaction_status
FAILED      12376
SUCCESS    237624
Name: transaction id, dtype: int64

## Transactions by size

In [49]:
df.groupby("transaction_size")["transaction id"].count()

transaction_size
Large      10959
Medium     81444
Small     157597
Name: transaction id, dtype: int64

## Average Revenue by Merchant Category

In [50]:
df.groupby("merchant_category")["amount (INR)"].mean().sort_values(ascending=False)

merchant_category
Education        5094.017636
Shopping         2573.085398
Utilities        2361.110305
Fuel             1555.383434
Grocery          1166.350979
Other             848.777550
Healthcare        542.853905
Food              531.694480
Entertainment     413.325374
Transport         308.003780
Name: amount (INR), dtype: float64

## Successful Transactions by merchant category

In [52]:
success = df[df["transaction_status"]=="SUCCESS"].groupby("merchant_category")["transaction id"].count()

total = df.groupby("merchant_category")["transaction id"].count()

((success/total)*100).sort_values(ascending=False)

merchant_category
Transport        95.239990
Fuel             95.196106
Healthcare       95.167022
Utilities        95.138329
Entertainment    95.075362
Other            95.045916
Food             94.992526
Grocery          94.990594
Shopping         94.914971
Education        94.748618
Name: transaction id, dtype: float64

## Average Revenue by Receiver Bank

In [53]:
df.groupby("receiver_bank")["amount (INR)"].mean().sort_values(ascending=False)

receiver_bank
SBI         1323.629902
Axis        1320.729754
Kotak       1316.031086
Yes Bank    1313.071254
HDFC        1305.608775
ICICI       1303.431005
IndusInd    1302.618791
PNB         1296.677808
Name: amount (INR), dtype: float64

## Average Revenue by Sender Bank

In [54]:
df.groupby("sender_bank")["amount (INR)"].mean().sort_values(ascending=False)

sender_bank
HDFC        1328.296492
SBI         1320.985118
Kotak       1313.668730
Yes Bank    1307.018383
IndusInd    1304.680054
PNB         1301.890964
ICICI       1301.057913
Axis        1296.722706
Name: amount (INR), dtype: float64

## Transactions by Sender State

In [56]:
df.groupby("sender_state")["transaction id"].count().sort_values(ascending=False)

sender_state
Maharashtra       37427
Uttar Pradesh     30125
Karnataka         29756
Tamil Nadu        25367
Delhi             24870
Telangana         22435
Gujarat           20061
Andhra Pradesh    20006
Rajasthan         19981
West Bengal       19972
Name: transaction id, dtype: int64

## Succesful Transactions by Network Type

In [58]:
df[df["transaction_status"]=="SUCCESS"].groupby("network_type")["transaction id"].count().sort_values(ascending=False)

network_type
4G      142349
5G       59543
WiFi     23912
3G       11820
Name: transaction id, dtype: int64

## Fraud Rate

In [59]:
fraud = df["fraud_flag"].sum()

total = len(df)

(fraud/total)*100

np.float64(0.192)

## Total Revenue by Receiver Bank

In [60]:
df.groupby("receiver_bank")["amount (INR)"].sum().sort_values(ascending=False)

receiver_bank
SBI         82565386
HDFC        49157476
ICICI       39029938
Axis        33007678
Yes Bank    32838599
IndusInd    32677495
PNB         32160203
Kotak       26502234
Name: amount (INR), dtype: int64

## Average Revenue by Sender Age Group

In [61]:
df.groupby("sender_age_group")["amount (INR)"].mean().sort_values(ascending=False)

sender_age_group
36-45    1424.041242
46-55    1333.129141
26-35    1326.285239
18-25    1194.545449
56+      1187.568631
Name: amount (INR), dtype: float64

# Key Business Insights

- SBI generated the highest transaction revenue.
- Shopping was the highest revenue-generating merchant category.
- The transaction success rate exceeded 95%.
- Fraud rate remained below 1%, indicating a highly secure transaction environment.
- The 26–35 age group contributed the highest revenue.
- Android devices accounted for the majority of transactions.
- 4G was the most commonly used network type.
- Weekend and weekday revenue showed only a small difference.

# Conclusion

This project demonstrates end-to-end data analysis using Python and Pandas. The data was cleaned, transformed, and analyzed to generate actionable business insights. The same dataset was further visualized in Power BI using interactive dashboards and DAX measures, enabling stakeholders to monitor digital payment performance effectively.